### ISSUE TITLE
Icons seem to "inherit" colors from previous icon on the same page

### ISSUE THREAD

**Issue by markosandalj** [MKAbuMattar/react-fluentui-emoji#7]
It seems like different icons refer to the same svg defs so they "inherit" the colors from each other. Here is an example with Black Nib and Smirk Face: https://codesandbox.io/p/devbox/d3rstk?migrateFrom=sxmsl2

I tried going through the source code and even wanted to contribute but unfortunately I wasn't able to figure out how the conversion exactly works in little time I had,  so I'm filing this in hopes someone can help.

**Comment by MKAbuMattar** [comment]
Thanks for catching this! I'll check it out and get a fix out in the next version.
